CREATE TABLE users
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name                 VARCHAR(100)                            NOT NULL,
    last_name                  VARCHAR(100)                            NOT NULL,
    email                      VARCHAR(100)                            NOT NULL,
    username                   VARCHAR(100)                            NOT NULL,
    password                   VARCHAR(100)                            NOT NULL,
    birth_date                 date                                    NOT NULL,
    role                       VARCHAR(255),
    is_account_non_expired     BOOLEAN                                 NOT NULL,
    is_account_non_locked      BOOLEAN                                 NOT NULL,
    is_credentials_non_expired BOOLEAN                                 NOT NULL,
    is_enabled                 BOOLEAN                                 NOT NULL,
    authorities                UNKNOWN__JAVA.UTIL.LIST<ORG.SPRINGFRAMEWORK.SECURITY.CORE.GRANTEDAUTHORITY>,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);