spring.application.name=crtach-backend
spring.datasource.password=password
spring.datasource.username=postgres
spring.datasource.name=crtach_db
security.jwt.secret-key="TESTKEYaaaTESTKEYaaaTESTKEYaaaTESTKEYaaaTESTKEYaaaTESTKEYaaaTESTKEYaaaTESTKEYaaa"
security.jwt.expiration-time=360000
spring.datasource.url=jdbc:postgresql://localhost:5432/crtach_db